name: Test Project
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare build and bin directory
        run: |
          mkdir bin/

      - name: Check file in directory
        run: |
          ls -lR

      - name: Test build
        run: |
          make
      - name: Clean up
          make clean
